apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-kustomize
commonLabels:
  app: http-test-kustomize

resources:
  - service.yaml
  - deployment.yaml
  - namespace.yaml
